swagger: "2.0"
info:
    title: An api for clients
    description: This api manages clients with CRUD operations
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/v1/client:
        get:
            tags:
                - client
            summary: show client
            operationId: client#show
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ClientClientManagementResponseCollection'
            schemes:
                - http
    /api/v1/client/{ClientID}:
        get:
            tags:
                - client
            summary: get client
            operationId: client#get
            parameters:
                - name: ClientID
                  in: path
                  description: Client ID
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ClientGetResponseBody'
            schemes:
                - http
        post:
            tags:
                - client
            summary: add client
            operationId: client#add
            parameters:
                - name: ClientID
                  in: path
                  description: Client ID
                  required: true
                  type: string
                - name: AddRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ClientAddRequestBody'
                    required:
                        - ClientName
            responses:
                "201":
                    description: Created response.
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - client
            summary: Download ./gen/http/openapi.json
            operationId: client#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    ClientAddRequestBody:
        title: ClientAddRequestBody
        type: object
        properties:
            ClientName:
                type: string
                description: Client ID
                example: Repudiandae nesciunt nemo magnam eos.
        example:
            ClientName: Earum nihil totam adipisci ab corrupti consequuntur.
        required:
            - ClientName
    ClientClientManagementResponseCollection:
        title: 'Mediatype identifier: application/vnd.client; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ClientManagementResponse'
        description: ShowResponseBody is the result type for an array of ClientManagementResponse (default view)
        example:
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
    ClientGetResponseBody:
        title: 'Mediatype identifier: application/vnd.client; view=default'
        type: object
        properties:
            ClientID:
                type: string
                description: ID is the unique id of the Client.
                example: ABCDEF12356890
            ClientName:
                type: string
                description: Name of the Client
                example: John Doe Limited
        description: GetResponseBody result type (default view)
        example:
            ClientID: ABCDEF12356890
            ClientName: John Doe Limited
        required:
            - ClientID
            - ClientName
    ClientManagementResponse:
        title: 'Mediatype identifier: application/vnd.client; view=default'
        type: object
        properties:
            ClientID:
                type: string
                description: ID is the unique id of the Client.
                example: ABCDEF12356890
            ClientName:
                type: string
                description: Name of the Client
                example: John Doe Limited
        description: A ClientManagement type describes a Client of company. (default view)
        example:
            ClientID: ABCDEF12356890
            ClientName: John Doe Limited
        required:
            - ClientID
            - ClientName
